#+TITLE: Dan Griswold's Emacs configuration
#+startup: oddeven

* Header
# Time-stamp: "2026-03-25 10:36 hindemith"
#+PROPERTY: header-args :tangle yes
#+OPTIONS: toc:4 h:4

* Overview

My emacs settings in org.

I use one master init file, with a separate config file. I prefer using the customize-variable interface for setting many (most?) options. That differs, I realize, from the preference of a number of emacs gurus.

* GTD setup

Much of my workflow revolves around org mode. Here I try to explain my own approach to a "Getting Things Done" (GTD) methodology, and how I implement that in emacs.

** "inbox"

I consider an inbox to be a recepticle for possibly actionable material that is yet to be processed into my system. These are my inboxes: 
  - a [[https://www.staples.com/Staples-Black-Wire-Mesh-Letter-Tray-Sorter/product_828567][tray sorter]] for holding papers, folders, notebooks, receipts, my digital voice recorder
  - my email

I find it completely unnecessary to designate a computer file as "Inbox." That introduces an extra step that contributes nothing to my productivity.

Yet I do have a capturing step in org-mode. But it doesn't involve an inbox file, buffer, or section. Rather, I have the capture templates set up to handle just about any kind of activity I will enter. (This is one benefit of having reflected deeply on my work.) 


The next sections cover how I implement this.


** multiple GTD org files 

I have an org file for each major area of responsibility:
  - personal.org :: 
  - clerk.org :: the main job file
  - scholarship :: my academic writings and tasks

I have my org-agenda-custom-commands set up so that I can view the current NEXT actions sorted by major responsibility, and showing items only from org-agenda files that are relevant at that time. So, items from "personal.org" would not appear if I have indicated that I'm at work, while items from "trinity.org" would not appear I have said that I'm not at work.

** levels of focus and planning

I have a "terraced" view of my work, much like what David Allen is after when he talks about "runway," "10,000 ft," "20,000 ft" etc. From low to high:

  - tasks
  - projects
  - objectives
  - goals
  - areas of focus/responsibility
  - volitions
  - vista
  - values
  - vision

A bit more on this:

*Tasks* are the level of actual doing or discrete activity. Examples are "Ask Bob about lunch on Tuesday" or "send position description to Bill." They have the grammatical form of simply imperative verbs.

*Projects* are efforts or activities that require more than one task to complete. A project has coherence and direction, seen in the /point/ or /purpose/ of its multiple tasks. I find that when I have entered something as a task when it really is an not-yet-obvious project, I resist it. Reflecting on /why/ I'm resisting often helps me see that it is a project and must be broken up into discrete, actionable steps. A project is stated in the grammatical form of a past participle. Examples: "Printer fixed" or "Tax information collected"

*Objectives* are things I want or need to accomplish that may (or may not) have more than one project and that (I hope) abide by the S.M.A.R.T. acronym of goal setting: they are Specific, Measurable, Achievable, Relevant, and Time-bound. They take the grammatical form of the infinitive. Examples: "To file our taxes well in advance of the deadine" or "To supervise the production of a Policy and Procedures document."

*Goals* are broader plans for accomplishment that will take significant time and effort to accomplish and that are more clearly connected to or flow from my areas of focus, vision, guiding principals, and values. They have the form of "I will" statements. They may or may not be assigned a deadline.

** todo states

These three levels -- tasks, projects, and goals -- each have their own todo states:

  - tasks: MAYB, TODO, NEXT, WAIT, DONE, DROP
  - projects: PERHAPS, BREWING, CURRENT, SHIFTED, WRAPPED, CANCELED
  - goals: MUL, NOW, END, ZAP

The first state for each level are for things that are, in GTD parlance, "someday/maybe" items. Each level has at least two done states, one for a completed item and one for an abandoned one. Tasks and projects also have an additional done state, for things that are given over to someone else.

** org file layout

These main agenda org files share a similar structure (with variations):

   * Goals
   * (Unassigned) Projects
   * Tasks

Some will also have:

   * Areas of focus/responsibility

And a view will have:

   * Top Levels
   ** Vision
   ** Values
   ** Vista
   ** Volition
   ** Areas of focus/responsibility


** capturing

** agenda views

** Weekly review

* Startup and Core Packages
Set location for my customization file
 #+BEGIN_SRC emacs-lisp
   (setq custom-file "~/.emacs.d/lisp/emacs-custom.el")
   (load custom-file)
 #+END_SRC

 Try to ignore useless bytecomp warnings
 #+begin_src emacs-lisp
   (defun dont-delay-compile-warnings (fun type &rest args)
     (if (eq type 'bytecomp)
         (let ((after-init-time t))
           (apply fun type args))
       (apply fun type args)))
   (advice-add 'display-warning :around #'dont-delay-compile-warnings)
 #+end_src
 
Setup package manager and use-package
 #+BEGIN_SRC emacs-lisp
   (require 'package)
   (package-initialize)

   ;; Bootstrap `use-package'
   (unless (package-installed-p 'use-package)
     (package-refresh-contents)
     (package-install 'use-package))

   (use-package bind-key)

   ;; (use-package cl)
 #+END_SRC

Get emacs to see my own lisp stuff
 #+BEGIN_SRC emacs-lisp
   (push "/home/dan/.emacs.d/lisp" load-path)
 #+END_SRC

Load some of my stuff
 #+begin_src emacs-lisp
   (require 'dmg-display)
   (require 'dmg-etc)
   (require 'dmg-completion)
   (require 'dmg-info)
   (require 'dmg-org)
 #+end_src 


* Editing
** General editing prefs
 Helpful defaults and bindings
 #+BEGIN_SRC emacs-lisp
   ;; (bind-key "C-a" 'beginning-of-visual-line)
   ;; (bind-key "C-e" 'end-of-visual-line)
   (bind-key "C-h V" 'customize-variable)
   (bind-key "M-T" 'transpose-sentences)
   (bind-key [C-tab] 'other-window)
   (bind-key [M-BS] 'backward-kill-word)
   (bind-key "M-SPC" 'cycle-spacing)
   ;; Unbind Pesky Sleep Button
   (global-unset-key [(control z)])
   (global-unset-key [(control x)(control z)])
 #+END_SRC

 Enable these disabled commands
 #+BEGIN_SRC emacs-lisp
   (put 'downcase-region  'disabled nil)
   (put 'upcase-region    'disabled nil)
   (put 'scroll-left      'disabled nil)
   (put 'narrow-to-page   'disabled nil)
   (put 'narrow-to-region 'disabled nil)
   (put 'set-goal-column  'disabled nil)
 #+END_SRC

 #+BEGIN_SRC emacs-lisp
   (defalias 'yes-or-no-p 'y-or-n-p)

   (setq completion-ignored-extensions
         (append '(".log" ".xdv" ".dvi") completion-ignored-extensions)
         ispell-really-hunspell t
         lazy-lock-continuity-time nil
         lazy-lock-stealth-time nil
         x-super-keysym 'alt)


   (pending-delete-mode 1)

   (global-font-lock-mode t)
 #+END_SRC
  
 
 Abbreviations
  #+BEGIN_SRC emacs-lisp
    (setq-default abbrev-mode t)
    (read-abbrev-file "~/Dropbox/.myabbrevs")
    (diminish 'abbrev-mode)
 #+END_SRC
 
  
 Auto modes
 #+BEGIN_SRC emacs-lisp
   (push '("\\[tT]e[xX]\\'" . latex-mode) auto-mode-alist)
   (autoload 'lua-mode "lua-mode" "Lua editing mode." t)
   (add-to-list 'auto-mode-alist '("\\.lua$" . lua-mode))
   (add-to-list 'interpreter-mode-alist '("lua" . lua-mode))
   (add-to-list 'auto-mode-alist '("/var/log/.*" . syslog-mode))
   (add-to-list 'auto-mode-alist '("\\.\\([pP][Llm]\\|al\\)\\'" . cperl-mode))


   (defalias 'perl-mode 'cperl-mode)
 #+END_SRC

 Unfill paragraph
 #+BEGIN_SRC emacs-lisp
   (bind-key [f12] 'dmg-unfill-paragraph)
 #+END_SRC
  
** LaTeX
 #+BEGIN_SRC emacs-lisp
   (use-package tex
     :defer t
     :ensure auctex
     :hook ((LaTeX-mode . outline-minor-mode)
   	 (LaTeX-mode . variable-pitch-mode)
            (LaTeX-mode . flyspell-mode)
            (LaTeX-mode . TeX-fold-mode)
   	 (LaTeX-mode . dmg-add-tex-style)))

   (use-package latex
     :defer t
     :config
     (require 'dmg-latex)
     (bind-keys :map LaTeX-mode-map
                ("'" . dmg-emph)
                ([f6] . dmg-sermonsizes)
                ([f7] . dmg-mkverse)
                ([S-return] . "\\\\\n")))


 #+END_SRC

** Hydra
#+BEGIN_SRC emacs-lisp
  (use-package hydra
    :defer t
    :bind
    ([f9] . dmg-hydra-emoji-template/body)
    ([f8] . hydra-journal/body)

    :config
    (defhydra dmg-hydra-emoji-template (:color blue :hint nil)
      "
  _t_hink     _b_uy      _a_sk     _p_ick/decide
  _c_all      _l_ook     _w_rite   inbox _z_ero!
  "
      ("t" (insert "🤔"))
      ("b" (insert "🛒"))
      ("a" (insert "❓"))
      ("p" (insert "⛏"))
      ("c" (insert "📞"))
      ("z" (insert "📥0⃣"))
      ("l" (insert "🔎"))
      ("w" (insert "🖋")))

    (defhydra hydra-journal (:color blue
                             :hint nil)
      "
  _d_: Daily journal     _w_: Weekly journal     _m_: Monthly journal    _t_: Theo journal
  "
      ;; ("d" (dmg-new-journal-entry))
      ;; ("d" (org-roam-dailies-capture-today))
      ("d" (dmg-new-journal-daily-dentry))
      ("w" (dmg-new-journal-weekly-dentry))
      ("m" (dmg-new-journal-monthly-dentry))
      ("t" (dmg-new-theology-journal-entry))))

  (use-package needs_hydras
    :after (hydra)
    :bind ([f4] . dmg-hydra-needs-main/body))


     #+END_SRC

     This is pretty cool. It works like a speed command. Type a "<",
     and a hydra pops up for inserting org-mode block templates. I
     found it [[http://oremacs.com/2015/03/07/hydra-org-templates/][here]] (I think)

#+BEGIN_SRC emacs-lisp

    (defhydra hydra-org-template (:color blue :hint nil)
      "
  _c_enter  _q_uote    _L_aTeX:
  _l_atex   _e_xample  _i_ndex:
  _a_scii   _v_erse    _I_NCLUDE:
  _s_rc     ^ ^        _H_TML:
  _h_tml    ^ ^        _A_SCII:
  "
      ("s" (hot-expand "<s"))
      ("e" (hot-expand "<e"))
      ("q" (hot-expand "<q"))
      ("v" (hot-expand "<v"))
      ("c" (hot-expand "<c"))
      ("l" (hot-expand "<l"))
      ("h" (hot-expand "<h"))
      ("a" (hot-expand "<a"))
      ("L" (hot-expand "<L"))
      ("i" (hot-expand "<i"))
      ("I" (hot-expand "<I"))
      ("H" (hot-expand "<H"))
      ("A" (hot-expand "<A"))
      ("<" self-insert-command "ins")
      ("o" nil "quit"))

  (require 'org-tempo) ; Required from org 9 onwards for old template expansion
    ;; Reset the org-template expnsion system, this is need after upgrading to org 9 for some reason
  (setq org-structure-template-alist (eval (car (get 'org-structure-template-alist 'standard-value))))
  (defun hot-expand (str &optional mod header)
      "Expand org template.

  STR is a structure template string recognised by org like <s. MOD is a
  string with additional parameters to add the begin line of the
  structure element. HEADER string includes more parameters that are
  prepended to the element after the #+HEADER: tag."
      (let (text)
        (when (region-active-p)
          (setq text (buffer-substring (region-beginning) (region-end)))
          (delete-region (region-beginning) (region-end))
          (deactivate-mark))
        (when header (insert "#+HEADER: " header) (forward-line))
        (insert str)
        (org-tempo-complete-tag)
        (when mod (insert mod) (forward-line))
        (when text (insert text))))

  (define-key org-mode-map "<"
    (lambda () (interactive)
      (if (or (region-active-p) (looking-back "^"))
          (hydra-org-template/body)
        (self-insert-command 1))))

#+END_SRC

     I wanted a quick way to dired my frequently visited directories:

         #+begin_src emacs-lisp :tangle no
       (defhydra dmg-hydra-dired
         (:color blue :hint nil)
         "
       _c_SS _e_xCom _f_orms _m_SS _s_SS _t_op
       "
         ("c" (dirvish "~/HC/Committees/CSS/"))
         ("e" (dirvish "~/HC/Committees/ExCom/"))
         ("f" (dirvish "~/HC/Forms/"))
         ("m" (dirvish "~/HC/Committees/MSS/"))
         ("s" (dirvish "~/HC/Committees/SSS/"))
         ("t" (dirvish "~/HC/"))
         )

       (bind-key "C-c d" 'dmg-hydra-dired/body)
    #+end_src

    Here's a hydra for my current writing projects
    #+begin_src emacs-lisp
      (defhydra dmg-hydra-writingprojects
        (:color blue :hint nil)
        "
      _c_ Calling in Counterpoint
      _r_ Reformed theololgy
      _e_ Evangelicalism
      "
        ("c" (dired "~/Wp/Scholarship/CallingCounterpoint/"))
        ("r" (find-file "~/Wp/Scholarship/RCA_theology/intro_draft.org"))
        ("e" (find-file "~/Wp/Scholarship/Understanding Evangelicalism/theological markers.org")))

      (bind-key "C-c <f12>" 'dmg-hydra-writingprojects/body)

#+end_src
** Other stuff
#+BEGIN_SRC emacs-lisp
  (use-package persistent-scratch)
  (persistent-scratch-setup-default)

  (bind-key "M-l" 'dmg-downcase-word)

  (bind-key "M-c" 'dmg-capitalize-word)

  (unbind-key "M-.")
  (pdf-tools-install)

  (use-package lilypond-mode
    :defer t
    :mode ("\\.ly$" . LilyPond-mode)
    :load-path "/usr/share/emacs/site-lisp/"
    :hook (LilyPond-mode . turn-on-font-lock))

  (use-package hl-line
    :defer t
    :config
    (set-face-background 'hl-line "moccasin"))

  (require 'smartparens-config)
  (require 'smartparens-org)
  (smartparens-global-mode t)
  (define-key smartparens-mode-map (kbd "C-M-f") 'sp-forward-sexp)
  (define-key smartparens-mode-map (kbd "C-M-b") 'sp-backward-sexp)
  (define-key smartparens-mode-map (kbd "C-M-d") 'sp-down-sexp)
  (define-key smartparens-mode-map (kbd "C-M-a") 'sp-backward-down-sexp)
  (define-key smartparens-mode-map (kbd "C-S-a") 'sp-beginning-of-sexp)
  (define-key smartparens-mode-map (kbd "C-S-e") 'sp-end-of-sexp)
  (define-key smartparens-mode-map (kbd "M-.") '  sp-backward-unwrap-sexp)


  (require 'titlecase)

  (global-set-key (kbd "C-c C-o") 'find-file-at-point)
 #+END_SRC

* Tools
** dired
 #+BEGIN_SRC emacs-lisp
   (require 'dmg-dired)
 #+END_SRC

** etc
 #+BEGIN_SRC emacs-lisp
   (use-package dictionary
     :defer t
     :bind ([mouse-3] . dictionary-mouse-popup-matching-words))

    (setq epa-file-encrypt-to '("kc5gmr@gmail.com"))
    (setq auto-save-file-name-transforms
          `((".*" "~/.emacs.d/autosaves/" t)))

    ;; (load "~/.emacs.d/lisp/o2b.el") ; org2blog and other credentials

     

   (use-package calendar
     :hook (calendar-mode . set-buffer-to-small)
     :config
     (defun set-buffer-to-small ()
       (face-remap-add-relative 'default '(:height 75))))

   (add-to-list 'load-path "/home/dan/.emacs.d/lisp/meme-master/")

   (use-package meme
     :commands (meme meme-file))

   (which-key-mode -1)
 #+END_SRC

** custom mode line
#+begin_src emacs-lisp
(require 'dmg-mode-line)
#+end_src

** show font
#+begin_src emacs-lisp
  (require 'show-font)
#+end_src

** pdf-tools
Just trying this out. Maybe it can eventually replace Evince
#+begin_src emacs-lisp
  (pdf-loader-install)
#+end_src

** casual
#+begin_src emacs-lisp :tangle yes
  (require 'dmg-casual)
#+end_src

* Final setup

 Have *scratch* buffer set up right
 #+BEGIN_SRC emacs-lisp
   (with-current-buffer "*scratch*"
     (org-superstar-mode 1)
     
     (visual-line-mode))
 #+END_SRC

 Get my Google calendar set up in diary
  #+BEGIN_SRC emacs-lisp :tangle yes
    (unless (file-exists-p "~/Dropbox/Management/cal.org")
      (dmg-get-gcal))
    (unless (file-updated-today-p "~/Dropbox/Management/cal.org")
      (dmg-get-gcal))
  #+END_SRC

 Start server and reset frame parameters
  #+BEGIN_SRC emacs-lisp :tangle no
    (unless (string-equal system-name "brahms")
      (server-start)
      (dmg-reset-frame-params))
  #+END_SRC

  Diminish some modes
  #+begin_src emacs-lisp :tangle yes
    (diminish 'org-pretty-tags-mode)
    (diminish 'visual-line-mode)
    (diminish 'buffer-face-mode)
  #+end_src

  I don't know why this doesn't work right on Brahms. I have to put this down here for it to work.
  #+begin_src emacs-lisp :tangle no
    (if (string-equal system-name "brahms")
        (org-pretty-tags-global-mode))
  #+end_src

  Hopefully speed some things up
  #+begin_src emacs-lisp :tangle yes
    (setq auto-window-vscroll nil)
  #+end_src

  Encouragement!
  #+begin_src emacs-lisp :tangle yes
    (start-process "encouragement" nil "encouragement.sh")
  #+end_src  


* Config
# Local Variables:
# eval: (add-hook 'after-save-hook (lambda () (widen) (org-babel-tangle)) nil t)
# End:
